### PR TITLE
Added Teamworkdesk.com

### PR DESCRIPTION
**Pull request by RobertJGabriel**

### CODE REVIEW

**Comment by RobertJGabriel** [comment]
@abraham @adactio @shwetank @PaulKinlan @erikjung 

Any update on this guys. Would love to get it live so we can link to you on the company blog.

**Comment by RobertJGabriel** [comment]
@abraham @adactio @shwetank @PaulKinlan @erikjung

Im happy to maintain this too btw if you guys are stuck for time.  :)

**Comment by abraham** [comment]
I'm not a maintainer of this project.

**Comment by RobertJGabriel** [comment]
@abraham Sorry dude. Your name came up in the suggestions :)

**Comment by RobertJGabriel** [comment]
@mathiasbynens

Incase you see this

**Comment by timwickey** [comment]
Yeah, this repo is dead unfortunately. @RobertJGabriel

**Comment by timwickey** [comment]
We have built an app store for Progressive web-apps tho it might not be a fit for an established site such as yours. Check it out though! https://wickeyappstore.com/

**Comment by RobertJGabriel** [comment]
Sweet @timwickey a guy can dream this isnt dead

**Comment by timwickey** [comment]
@RobertJGabriel PWA's are the future!

**Pull request closed without merging**
