### PR TITLE
Added KIBU (www.kibumap.com) scores 80+ on Google Lighthouse

### PR DESCRIPTION
**Pull request by Kiel-H-Byrne**
Hi there! PWA.Rocks does indeed rock. thank you for creating it. 
I'd like to add my app to the gallery as well, it's a tool to locate business in the USA owned by specific demographic group.

### CODE REVIEW

**Comment by andreasbovens** [comment]
What does this app do?

**Comment by tdotholla** [comment]
Client requested an app to locate minority-owned businesses in the USA. 
App uses geolocation and browser IP to show closest businesses. 
I actually need to deploy a major update to production, so it will soon have more robusT you and searching capabilities.

You rock!

**Comment by tdotholla** [comment]
i deployed those updates. lighthouse score back up to 90s, better icons for devices, other changes. 
should i submit another pull request?

**Comment by timwickey** [comment]
Hey @tdotholla! Are you still building PWA's? Would love to chat tim@wickeyappstore.com

**Comment by Kiel-H-Byrne** [comment]
@timwickey I am!

**Pull request closed without merging**
