### PR TITLE
Add Polytimer

### PR DESCRIPTION
**Pull request by davi-mbatista**
This is a pull request for adding https://polytimer.rocks to the list. Polytimer is a ultility/experiment pwa for setting timers. It uses Polymer and service worker.

### CODE REVIEW

**Comment by davi-mbatista** [comment]
Something else to optimize?  😃

**Comment by andreasbovens** [comment]
Looking good! Merging 👍

**Comment by davi-mbatista** [comment]
When the new version is going live? 😄

**Comment by mathiasbynens** [comment]
@davi-mbatista It’s already live. The website is updated automatically on every push to master.

**Comment by davi-mbatista** [comment]
Ow... I can't find the app that was added on this pull request though.

**Comment by pepelsbey** [comment]
@mathiasbynens, we're currently having problems with auto deploy, could you please have a look?

**Comment by mathiasbynens** [comment]
@pepelsbey Done.

**Comment by davi-mbatista** [comment]
@mathiasbynens @pepelsbey Awesome!

**Pull request merged**
